[package]
name = "node-runtime"
build = "build.rs"
edition = "2018"
version = "2.0.0"
authors = ["trust dev"]
license = 'Apache-2.0'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
static_assertions = "1.1.0"
hex-literal = { version = "0.3.1", optional = true }
log = { version = "0.4.14", default-features = false }

# primitives
sp-authority-discovery = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-consensus-babe = { version = "0.9.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, version = "3.0.0"}
sp-inherents = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
node-primitives = { version = "2.0.0", default-features = false, path = "../primitives" }
sp-offchain = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-core = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-std = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-api = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-runtime = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-staking = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-keyring = { version = "3.0.0", optional = true, git = "https://github.com/paritytech/substrate" }
sp-session = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-transaction-pool = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-version = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-npos-elections = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }

# frame dependencies
frame-executive = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
frame-benchmarking = { version = "3.1.0", default-features = false, git = "https://github.com/paritytech/substrate", optional = true }
frame-support = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
frame-system = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
frame-system-benchmarking = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", optional = true }
frame-election-provider-support = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
frame-system-rpc-runtime-api = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
frame-try-runtime = { version = "0.9.0", default-features = false, git = "https://github.com/paritytech/substrate", optional = true }
pallet-assets = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-authority-discovery = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-authorship = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-babe = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-balances = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-bounties = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-collective = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-contracts = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-contracts-primitives = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-contracts-rpc-runtime-api = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-democracy = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-election-provider-multi-phase = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-elections-phragmen = { version = "4.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-gilt = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-grandpa = { version = "3.1.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-im-online = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-indices = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-identity = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-lottery = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-membership = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-mmr = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-multisig = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-offences = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-offences-benchmarking = { version = "3.0.0", git = "https://github.com/paritytech/substrate", default-features = false, optional = true }
pallet-proxy = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-randomness-collective-flip = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-recovery = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-session = { version = "3.0.0", features = ["historical"], git = "https://github.com/paritytech/substrate", default-features = false }
pallet-session-benchmarking = { version = "3.0.0", git = "https://github.com/paritytech/substrate", default-features = false, optional = true }
pallet-staking = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-staking-reward-curve = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-scheduler = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-society = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-sudo = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-timestamp = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-tips = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-treasury = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-utility = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-transaction-payment = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-transaction-payment-rpc-runtime-api = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-transaction-storage = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-uniques = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-vesting = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }

max-encoded-len = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", features = [ "derive" ] }
[build-dependencies]
substrate-wasm-builder = { version = "4.0.0", git = "https://github.com/paritytech/substrate" }

[dev-dependencies]
sp-io = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }

[features]
default = ["std"]
with-tracing = [ "frame-executive/with-tracing" ]
std = [
	"sp-authority-discovery/std",
	"pallet-assets/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"sp-consensus-babe/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-bounties/std",
	"sp-block-builder/std",
	"codec/std",
	"pallet-collective/std",
	"pallet-contracts/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	"frame-executive/std",
	"pallet-gilt/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"sp-inherents/std",
	"pallet-lottery/std",
	"pallet-membership/std",
	"pallet-mmr/std",
	"pallet-multisig/std",
	"pallet-identity/std",
	"pallet-scheduler/std",
	"node-primitives/std",
	"sp-offchain/std",
	"pallet-offences/std",
	"pallet-proxy/std",
	"sp-core/std",
	"pallet-randomness-collective-flip/std",
	"sp-std/std",
	"pallet-session/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-staking/std",
	"sp-keyring",
	"sp-session/std",
	"pallet-sudo/std",
	"frame-support/std",
	"frame-benchmarking/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-timestamp/std",
	"pallet-tips/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-storage/std",
	"pallet-treasury/std",
	"sp-transaction-pool/std",
	"pallet-utility/std",
	"sp-version/std",
	"pallet-society/std",
	"pallet-recovery/std",
	"pallet-uniques/std",
	"pallet-vesting/std",
	"log/std",
	"frame-try-runtime/std",
	"sp-npos-elections/std",
	"max-encoded-len/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-election-provider-multi-phase/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-bounties/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-contracts/runtime-benchmarks",
	"pallet-democracy/runtime-benchmarks",
	"pallet-elections-phragmen/runtime-benchmarks",
	"pallet-gilt/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-lottery/runtime-benchmarks",
	"pallet-membership/runtime-benchmarks",
	"pallet-mmr/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-society/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-tips/runtime-benchmarks",
	"pallet-transaction-storage/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-uniques/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"pallet-offences-benchmarking",
	"pallet-session-benchmarking",
	"frame-system-benchmarking",
	"hex-literal",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-try-runtime",
	"frame-system/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-bounties/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-contracts/try-runtime",
	"pallet-democracy/try-runtime",
	"pallet-elections-phragmen/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-lottery/try-runtime",
	"pallet-membership/try-runtime",
	"pallet-mmr/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-identity/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-randomness-collective-flip/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-election-provider-multi-phase/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-tips/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-society/try-runtime",
	"pallet-recovery/try-runtime",
	"pallet-uniques/try-runtime",
	"pallet-vesting/try-runtime",
	"pallet-gilt/try-runtime",
]
# Make contract callable functions marked as __unstable__ available. Do not enable
# on live chains as those are subject to change.
contracts-unstable-interface = [
	"pallet-contracts/unstable-interface"
]
